name:                panvis
version:             0.1.0.0
github:              "meierk/visualisierung-von-coronadaten"
license:             BSD3
author:              "Korbinian Meier, Leonard Ganz, Pierre Franke"
maintainer:          "leonard.ganz@campus.lmu.de"
copyright:           "2022 Korbinian Meier, Leonard Ganz, Pierre Franke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at <https://gitlab2.cip.ifi.lmu.de/meierk/visualisierung-von-coronadaten#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-conduit
- aeson

library:
  source-dirs: src

executables:
  panvis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - panvis

tests:
  panvis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - panvis
